"""empty message

Revision ID: 812c7465297a
Revises: defc6847a6c6
Create Date: 2023-12-28 12:49:59.145912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '812c7465297a'
down_revision: Union[str, None] = 'defc6847a6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Questions', sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Questions', 'answer')
    # ### end Alembic commands ###
