"""add unique tag to models

Revision ID: d89e53a0cf04
Revises: a99b435ce084
Create Date: 2023-12-28 16:30:22.964241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd89e53a0cf04'
down_revision: Union[str, None] = 'a99b435ce084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Categories', ['name'])
    op.drop_index('ix_Questions_title', table_name='Questions')
    op.create_index(op.f('ix_Questions_title'), 'Questions', ['title'], unique=True)
    op.create_unique_constraint(None, 'Questions', ['text'])
    op.drop_index('ix_Users_email', table_name='Users')
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_unique_constraint(None, 'Users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.create_index('ix_Users_email', 'Users', ['email'], unique=False)
    op.drop_constraint(None, 'Questions', type_='unique')
    op.drop_index(op.f('ix_Questions_title'), table_name='Questions')
    op.create_index('ix_Questions_title', 'Questions', ['title'], unique=False)
    op.drop_constraint(None, 'Categories', type_='unique')
    # ### end Alembic commands ###
