name: Main CI

on:
    push:
        branches: [ main ]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.11
            -   name: Install requirements
                run: pip install -r requirements.txt
            -   name: Create env file
                run: echo "${{ secrets.ENV_FILE }}" > .env
            -   name: Run tests
                run: pytest .
    production:
        runs-on: ubuntu-latest
        needs: [ tests ]
        steps:
            -   name: Create env file
                run: echo "${{ secrets.ENV_PROD }}" > .env
            -   name: Login SSH
                uses: appleboy/ssh-action@v1.0.3
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USER }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    port: ${{ secrets.SSH_PORT }}
                    script: |
                        cd Interviewer/
                        git pull
                        docker compose stop
                        docker compose up
